name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

env:
#  The default GIT_AUTHOR_NAME is github.actor
  GIT_AUTHOR_NAME: ${{ github.actor }}
#  The default GIT_AUTHOR_NAME is github.actor@users.noreply.github.com
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  WIKI: wiki
  DOCS: docs

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@master
        with:
          source: ${{ env.DOCS }}
          destination: ${{ env.WIKI }}
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
#          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
#          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          commitMessage: Auto sync ${{ env.DOCS }} to ${{ env.WIKI }} [skip actions]
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    # I have to check '[skip actions]' here because it is NOT supported for the `gollum` event.
    if: github.event_name == 'gollum' # && !contains(${{ env.WIKI_COMMIT_MESSAGE }}, '[skip actions]')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
          ref: ${{ env.default_branch }}
      - uses: actions/github-script@v4
        with:
          script: |
            console.log('github:', github)
            console.log('context:', context)
            console.log('core:', core)
            console.log('glob:', glob)
            console.log('io:', io)
            console.log('context.context.payload.repository.owner', context.context.payload.repository.owner)
            result = await github.rest.git.getCommit({
              context.context.payload.repository.owner.login,
              context.payload.repository.name,
              context.sha,
            })
            console.log('result:', result)
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@master
        with:
          source: ${{ env.WIKI }}
          destination: ${{ env.DOCS }}
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
#          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
#          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: ${{ env.default_branch }}
          commitMessage: Auto sync ${{ env.WIKI }} to ${{ env.DOCS }} [skip actions]
