# This workflow will check if terms are outdated or not.

name: Outdated checker
on: 
  pull_request:
#     paths:
#       - 'content/**'
#     branches:
#       - 'dev-**'

jobs:
  check-outdated:
    strategy:
      matrix:
        branch: [ dev-ko ] # other branches and be added.
    runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    
#     - name: Extract branch name
#       shell: bash
#       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/})"
#       id: extract_branch
      
#     - name: Checkout ${{ matrix.branch }} (base branch)
#       uses: actions/checkout@v3
#       with:
#         ref: ${{ matrix.branch }}
      
    - name: Check Git status
      shell: bash
      run: |
        ls -al
        git status
        git branch        
        echo "GITHUB_REF: $GITHUB_REF"
        echo "github.ref: ${{github.ref}}"
        echo "github.head_ref: ${{github.head_ref}}"
        echo "github.base_ref: ${{github.base_ref}}"
      
    - name: Get list of localized terms
      shell: bash
      run: |
        echo "this will show a list"
        
              
    - name: Check outdated
      run: |        
        EXTRACT_BRANCH=${GITHUB_REF#refs/}
        echo EXTRACT_BRANCH
        git diff ${EXTRACT_BRANCHE}..origin/${{ matrix.branch }}
