# This workflow will check if terms are outdated or not.

name: Outdated checker
on: 
  pull_request:
#     paths:
#       - 'content/**'
#     branches:
#       - 'dev-**'

jobs:
  check-outdated:
    strategy:
      matrix:
        branch: [ dev-ko ] # other branches and be added.
    runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Checkout ${{ matrix.branch }} (base branch)
      uses: actions/checkout@v3
      with:
        ref: ${{ matrix.branch }}
      
    - name: Check Git status
      shell: bash
      run: |
        ls -al
        git status
        git branch
      
    - name: Get list of localized terms
      shell: bash
      run: |
        echo "this will show a list"
              
    - name: Check outdated
      run: |
        git diff ${{ matrix.branch }} ${{github.ref}}
