name: Post outdated checkering result

on:
  workflow_run:
    workflows: ["Outdated checker"]
    types:
      - completed           
      
jobs:
  post-result:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write      

    steps:

#     NOTE - "actions/download-artifact" is not working for sharing data between workflows. 
#     - name: Download result
#       uses: actions/download-artifact@v3
    - name: Download result
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: outdated-checker.yaml
        workflow_conclusion: success
        
    - name: Display structure of downloaded files
      run: tree
        
    - name: Generate a result markdown
      shell: bash
      run: |
        FILE_LIST=$(find ./dev-ko-outdated-checking-result/ -name '*.md')
        VALUE=$(cat ${FILE_LIST[0]})
        
        # Create checking_result.md
        cat > output.md <<EOF      
        ### Outdated files        
        ${FILE_LIST}
        
        ### Outdated content                
        Filename:   
        ${FILE_LIST[0]}
        
        Content:   
        ${VALUE}        
        
        EOF
        
    - name: Create an issue from file    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: An example issue
        content-filepath: output.md
        labels: |
          outdated
          lang/ko
