name: Port outdated checking result

on:
  workflow_run:
    workflows: ["Outdated checker"]
    types:
      - completed           
      
jobs:
  post-result:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write      

    steps:
#     - name: Checkout 
#       uses: actions/checkout@v3

# Important! "actions/download-artifact" is not working for sharing data between workflows. 
#     - name: Download result
#       uses: actions/download-artifact@v3

    - name: Download result
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: outdated-checker.yaml
        workflow_conclusion: success
        
    - name: Display structure of downloaded files
      run: ls -R
        
    - name: Generate a result markdown
      shell: bash
      run: |
        VALUE=`cat outdated-file-list.txt`
        
        # Create checking_result.md
        cat > output.md <<EOF      
        ### Outdated files
        
        ${VALUE}
        
        EOF
        
    - name: Create an issue from file    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: An example issue
        content-filepath: output.md
        labels: |
          test
