name: Post outdated checkering result

on:
  workflow_run:
    workflows: ["Outdated checker"]
    types:
      - completed           
      
jobs:
  post-result:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write      

    env:
      ARTIFACT_DIR: ./dev-ko-outdated-checking-result/ # It will be updated.

    steps:

#     NOTE - "actions/download-artifact" is not working for sharing data between workflows. 
#     - name: Download result
#       uses: actions/download-artifact@v3
    - name: Download result
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: outdated-checker.yaml
        workflow_conclusion: success
        
    - name: Display structure of downloaded files
      run: tree
        
    - name: Generate a result markdown
      shell: bash
      run: |
        FILE_LIST=$(find ${ARTIFACT_DIR} -name '*.md')
        
        # Create checking_result.md
        touch output.md
        
        # Generate markdown
        echo "### Outdated files" >> output.md
        
        for FILE in ${FILE_LIST}; do 
          FILE_NAME="${FILE#${ARTIFACT_DIR}}" 
          echo "- ${FILE_NAME}" >> output.md
        done 
        
        echo "" >> output.md
        
        echo "### More details" >> output.md
        
        for FILE in ${FILE_LIST}; do 
          FILE_NAME="${FILE#${ARTIFACT_DIR}}" 
        
          echo "File: ${FILE_NAME}" >> output.md
          echo "" >> output.md
          echo "\`\`\`diff" >> output.md 
          cat ${FILE} >> output.md      
          echo "\`\`\`" >> output.md 
          
        done 
        
        echo "The end of report"  >> output.md              
        
    - name: Create an issue from file    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "[ko] A report to track update"
        content-filepath: output.md
        labels: |
          outdated
          good first issue
          lang/ko
